language: python
env: MOZ_UPHEADLINER_DEV=1
python:
  - "2.7"
services:
  - redis-server
# command to install dependencies
install: python setup.py install
# command to run the build
script: fab build
after_success:
  - coveralls
